### ISSUE TITLE
Setup issue / SASL issue / Smack issue?

### ISSUE THREAD

**Issue by imaginator** [buddycloud/buddycloud-media-server#98]
Trying to orchestrate the media server with https://github.com/buddycloud/saltstack/blob/master/salt/buddycloud-media-server/init.sls but, when media operations that require a permissions check happen, I see the following log:

```
2015-08-25 15:24:03,475 ERROR com.buddycloud.mediaserver.Main - XMPP connection coudn't be started
org.jivesoftware.smack.XMPPException: No response from the server.
        at org.jivesoftware.smack.NonSASLAuthentication.authenticate(NonSASLAuthentication.java:73) ~[buddycloud-media-server-jar-with-dependencies.jar:na]
        at org.jivesoftware.smack.XMPPConnection.login(XMPPConnection.java:212) ~[buddycloud-media-server-jar-with-dependencies.jar:na]
        at org.jivesoftware.smack.Connection.login(Connection.java:348) ~[buddycloud-media-server-jar-with-dependencies.jar:na]
        at com.buddycloud.mediaserver.Main.createAndStartConnection(Main.java:222) [buddycloud-media-server-jar-with-dependencies.jar:na]
        at com.buddycloud.mediaserver.Main.startXMPPToolBox(Main.java:126) [buddycloud-media-server-jar-with-dependencies.jar:na]
        at com.buddycloud.mediaserver.Main.main(Main.java:56) [buddycloud-media-server-jar-with-dependencies.jar:na]
2015-08-25 15:24:03,626 ERROR com.buddycloud.mediaserver.Main - Error while starting XMPP client
com.buddycloud.mediaserver.commons.exception.XMPPException: No response from the server.
        at com.buddycloud.mediaserver.Main.createAndStartConnection(Main.java:231) [buddycloud-media-server-jar-with-dependencies.jar:na]
        at com.buddycloud.mediaserver.Main.startXMPPToolBox(Main.java:126) [buddycloud-media-server-jar-with-dependencies.jar:na]
        at com.buddycloud.mediaserver.Main.main(Main.java:56) [buddycloud-media-server-jar-with-dependencies.jar:na]
Caused by: org.jivesoftware.smack.XMPPException: No response from the server.
        at org.jivesoftware.smack.NonSASLAuthentication.authenticate(NonSASLAuthentication.java:73) ~[buddycloud-media-server-jar-with-dependencies.jar:na]
        at org.jivesoftware.smack.XMPPConnection.login(XMPPConnection.java:212) ~[buddycloud-media-server-jar-with-dependencies.jar:na]
        at org.jivesoftware.smack.Connection.login(Connection.java:348) ~[buddycloud-media-server-jar-with-dependencies.jar:na]
        at com.buddycloud.mediaserver.Main.createAndStartConnection(Main.java:222) [buddycloud-media-server-jar-with-dependencies.jar:na]
        ... 2 common frames omitted
```

According to https://github.com/buddycloud/saltstack/blob/master/salt/buddycloud-media-server/mediaserver.properties.template#L28 the client should be authenticating. 

If anyone can help debug this on `crater` so that I can get a working config for saltstack, that would be great!`

**Comment by lloydwatkin** [comment]
I believe this is because the media server either can't do secure connections or has an issue with non-plain auth. @dwd might be able to confirm from their deployment, and I'm also sure we've hit this before too with Project Isizwe server.

**Comment by imaginator** [comment]
Ok - yes... turning off all TLS requirements solves this. Looks like smack doesn't do what it's documentation suggests regarding TLS. Thanks @lloydwatkin
